# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
jobs:
- job: Cleanup
  workspace:
    clean: all
- deployment: Build Image
  displayName: Staging
  environment:
    name: env
    resourceType: VirtualMachine
    resourceName: vm-cicd
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - bash: "who"
        - script: |
            echo $(Build.SourcesDirectory)
            ls $(Build.SourcesDirectory) *
            cd 01-hello-world-rest-api
            sudo mvn clean install
            sudo docker login
            sudo docker push dineshrvl/hello-world-rest-api:0.0.4-SNAPSHOT

