# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
jobs:
- deployment: VMDeploy
  displayName: web
  environment:
    name: Env1
    resourceType: VirtualMachine
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - bash: "who"
        - script: |
            echo $(Build.SourcesDirectory)
            ls $(Build.SourcesDirectory) *
            cd 01-hello-world-rest-api
            sudo mvn clean install
